services:
  postgres:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret

  backend_22:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://admin:secret@postgres:5432/mydb

volumes:
  postgres_data:
